server:
    port: 8080

spring:
    elasticsearch:
        uris: 127.0.0.1
        password: <password>
        username: <username>
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/mirror_of_law?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: <username>
        password: <password>
        type: com.alibaba.druid.pool.DruidDataSource

logging:
    level:
        root: INFO
        com.baomidou.mybatisplus: DEBUG
        team.semg04.themirroroflaw.user.mapper: DEBUG
    file:
        name: logs/TheMirrorOfLaw.log

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
        aggressive-lazy-loading: true
    global-config:
        db-config:
            id-type: AUTO